### PR TITLE
Interface should indicate server-side changes

### PR DESCRIPTION
**Pull request by ericclemmons**
From #5, when the server updates, the interface should indicate that.

### CODE REVIEW

**Comment by ericclemmons** [comment]
I **love** this feature!  More to do, but:

1. `yarn example custom-server`. 
2. Open demo & browser console
3. Edit `server/index.js` and change log messages.
4. **Watch the browser console log out server-side messages!**

**Comment by cdonohue** [comment]
This looks great! It might also be helpful to utilize console styling to differentiate `client` and `server` errors. For example, a client error would be red foreground color, while a server error would be a red background color.

**Comment by ericclemmons** [comment]
@cdonohue You & I think a lot alike ;) 7b87f42

**Comment by ericclemmons** [comment]
I can't find a good way to find out that the server is re-building _before_ it rebuilds.  Only once it's built & it's being re-loaded.

This may be good enough, but I'm thinking of punting on that functionality since an API is usually requested on load, vs. every second.

**Instead, I think I'd rather look into the double-save to reload feature**.

**Pull request merged**
